### ISSUE TITLE
Remove assets from git to reduce repository size

### ISSUE THREAD

**Issue by MarconZet** [adkuba/Gravity#68]
The size of the repository is absurd, nearly 400 MB.

Consider using [Git Large File Storage](https://git-lfs.github.com).

**Comment by MarconZet** [comment]
Never mind you are actually using `git-lfs`. Did you migrate using `git-lfs-migrate`?

**Comment by adkuba** [comment]
Używałem git lfs ale jest płatne i wyłączyłem, niestety to był mój pierwszy projekt i nie uważałem na wielkość repo xD Żeby wystartować ten projekt trzeba mieć paczkę z asset store która kupiłem
